#!/bin/bash



if [ -f /etc/environment ]; then
     source /etc/environment
fi

IPS_1=`cat /etc/haproxy/dns.backends`
python3 /configure.py dns
IPS_2=`cat /etc/haproxy/dns.backends`

if [ "$IPS_1" != "$IPS_2" ]; then
  echo "DNS backends changed: $IPS_2"
  kill -s HUP 1
fi
