#!/bin/bash

if ps ax | grep $0 | grep -v $$ | grep bash | grep -v grep
then
   echo "The script is already running."
   exit 1
fi


if [ -f /etc/environment ]; then
     . /etc/environment
fi

IPS_1=`cat /etc/haproxy/dns.backends`
python3 /configure.py dns
IPS_2=`cat /etc/haproxy/dns.backends`

if [ "$IPS_1" != "$IPS_2" ]; then
  echo "DNS backends changed: $IPS_2"
  reload
fi
